paire
Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

diff --git a/mx-rdma-tools/image/tools/testRdmaPair b/mx-rdma-tools/image/tools/testRdmaPair
--- a/mx-rdma-tools/image/tools/testRdmaPair
+++ b/mx-rdma-tools/image/tools/testRdmaPair
@@ -4,7 +4,7 @@
 # SPDX-License-Identifier: Apache-2.0
 
 :<<EOF
-让每两两的主机之间，同轨网卡同时打满流程
+同时进行两两主机之间的打流测试，包括同轨和跨轨网卡打流，在两个主机之间打流时，ASYNCHRONOUS=true 是让8个网卡同时打流，还是一个一个网卡打
 
 example1:
     DURATION=30 LOOP_TIMES=2 ASYNCHRONOUS=true  ./testRdmaPair
@@ -105,16 +105,22 @@ RunClient() {
     RESULT_FILE="${RESULT_DIR}/${REMOTE_SERVER}"
 
     echo "" >>${RESULT_FILE}
-    printf "_____________________________________________________________________________________________________________________________________________________\n" >>${RESULT_FILE}
-    printf "%-40s\t%-40s\t%-20s%-20s%-20s\n" "from ${REMOTE_CLIENT} ${REMOTE_CLIENT_NAME}" "to ${REMOTE_SERVER} ${REMOTE_SERVER_NAME}" "BW avg[Gb/sec]" "MsgRate[Mpps]" "maxSpeed" >>${RESULT_FILE}
+    printf "________________________________________________________________________________________________________________________________________________\n" >>${RESULT_FILE}
+    printf "%-40s\t%-40s\t%-20s%-20s%-20s%-20s\n" "from ${REMOTE_CLIENT} ${REMOTE_CLIENT_NAME}" "to ${REMOTE_SERVER} ${REMOTE_SERVER_NAME}" "BW avg[Gb/sec]" "MsgRate[Mpps]" "maxSpeed" "sameNetworkTrack" >>${RESULT_FILE}
     printf "_____________________________________________________________________________________________________________________________________________________\n" >>${RESULT_FILE}
 
     REMOTE_RUN_OUTPUT_DIR="${REMOTE_OUTPUT_DIR}/${REMOTE_SERVER}"
     mkdir -p ${REMOTE_RUN_OUTPUT_DIR}
+
+    echo "-------------"
+    cat ${REMOTE_INFOR_DIR}/${REMOTE_CLIENT}
+    cat ${REMOTE_INFOR_DIR}/${REMOTE_SERVER}
+    echo "-------------"
+
+    # reset the port
     PORT=${START_PORT}
-
-
     while read LINE; do
+            echo "=== SERVER LINE: ${LINE}"
         REMOTE_DEVICE=$(echo "${LINE}" | awk '{print $1}')
         REMOTE_INTERFACE=$(echo "${LINE}" | awk '{print $2}')
         REMOTE_IP=$(echo "${LINE}" | awk '{print $3}')
@@ -123,63 +129,66 @@ RunClient() {
         REMOTE_INDEX=$(echo "${LINE}" | awk '{print $6}')
         [ -n "${REMOTE_DEVICE}" ] || continue 
 
-
+        #OLD=$IFS
+        #IFS=$'\n'
         while read CLIENT_LINE; do
+            #IFS=$OLD
+            echo "=== CLIENT_LINE: ${CLIENT_LINE}"
             LOCAL_DEVICE=$(echo "${CLIENT_LINE}" | awk '{print $1}')
             LOCAL_INTERFACE=$(echo "${CLIENT_LINE}" | awk '{print $2}')
             LOCAL_IP=$(echo "${CLIENT_LINE}" | awk '{print $3}')
             LOCAL_MASK=$(echo "${CLIENT_LINE}" | awk '{print $4}')
             LOCAL_PROTOCOL=$(echo "${CLIENT_LINE}" | awk '{print $5}')
             LOCAL_INDEX=$(echo "${CLIENT_LINE}" | awk '{print $6}')
+
             [ -n "${LOCAL_DEVICE}" ] || continue 
 
+            SAME_NETWORK_TRACK="false"
             if [ "${REMOTE_MASK}"x == "${LOCAL_MASK}"x ] && [ -n "${LOCAL_MASK}" ]; then
                 if CheckIPv4SameSubnet "${LOCAL_IP}" "${REMOTE_IP}" "${LOCAL_MASK}"; then
+                    SAME_NETWORK_TRACK="true"
+                fi 
+            fi
+            [ "${SAME_NETWORK_TRACK}"x == "true"x ] || continue
 
-                    echo ""
-                    echo "-------------------------------------------------------------------------------------------------"
-                    echo "${CURRENT_FILENAME} case: client node ${REMOTE_CLIENT}/${REMOTE_CLIENT_NAME} ( ${LOCAL_INTERFACE} ${LOCAL_DEVICE} ${LOCAL_IP} ) and the server ${REMOTE_SERVER}/${REMOTE_SERVER_NAME} ( ${REMOTE_INTERFACE} ${REMOTE_DEVICE} ${REMOTE_IP} )  "
+            echo ""
+            echo "-------------------------------------------------------------------------------------------------"
+            echo "${CURRENT_FILENAME} case: client node ${REMOTE_CLIENT}/${REMOTE_CLIENT_NAME} ( ${LOCAL_INTERFACE} ${LOCAL_DEVICE} ${LOCAL_IP} ) and the server ${REMOTE_SERVER}/${REMOTE_SERVER_NAME} ( ${REMOTE_INTERFACE} ${REMOTE_DEVICE} ${REMOTE_IP} )  "
 
-                    REMOTE_RUN_IP_OUTPUT_DIR="${REMOTE_RUN_OUTPUT_DIR}/${REMOTE_IP}"
+            REMOTE_RUN_IP_OUTPUT_DIR="${REMOTE_RUN_OUTPUT_DIR}/${REMOTE_IP}"
 
-                    MAX_SPEED=$(ethtool ${LOCAL_INTERFACE} | grep Speed | awk '{print $2}')
-                    #if ! ping -I ${LOCAL_INTERFACE} -c 2 ${REMOTE_IP} &>/dev/null; then
-                    #    echo "error, failed to ping remote ${REMOTE_IP} from local interface ${LOCAL_INTERFACE}"
-                    #    printf "%-40s\t%-40s\t%-20s%-20s%-20s\n" "${LOCAL_INTERFACE}/${LOCAL_DEVICE}/${LOCAL_IP}" "${REMOTE_INTERFACE}/${REMOTE_DEVICE}/${REMOTE_IP}" "failure" "failure" "${MAX_SPEED}" >>${RESULT_FILE}
-                    #else
-                        OPTIONS="-d ${LOCAL_DEVICE} -x ${LOCAL_INDEX} -p ${PORT} ${CMD_OPTIONS} ${REMOTE_IP}"
-                        echo "client on ${REMOTE_CLIENT}/${REMOTE_CLIENT}: ${CMD_CLI} ${OPTIONS}"
-                        if [ "${ASYNCHRONOUS}"x == "true"x ]; then
-                        (
-                            { ssh  -p ${ENV_SSH_PORT} ${REMOTE_CLIENT} ${CMD_CLI} ${OPTIONS} | tee ${REMOTE_RUN_IP_OUTPUT_DIR}; } || true
-                            BANDWITDH=$(cat ${REMOTE_RUN_IP_OUTPUT_DIR} | grep -A 1 "BW average" | grep -E "[0-9\.]+" | awk '{print $4 }') || true
-                            PPS=$(cat ${REMOTE_RUN_IP_OUTPUT_DIR} | grep -A 1 "BW average" | grep -E "[0-9\.]+" | awk '{print $5 }') || true
-                            if [ -n "${BANDWITDH}" ]; then
-                                printf "%-40s\t%-40s\t%-20s%-20s%-20s\n" "${LOCAL_INTERFACE}/${LOCAL_DEVICE}/${LOCAL_IP}" "${REMOTE_INTERFACE}/${REMOTE_DEVICE}/${REMOTE_IP}" "${BANDWITDH}" "${PPS}" "${MAX_SPEED}" >>${RESULT_FILE}
-                            else
-                                echo "error, ${REMOTE_CLIENT}/${REMOTE_CLIENT_NAME}( ${LOCAL_INTERFACE} ${LOCAL_DEVICE} ${LOCAL_IP} ) failed to test server ${REMOTE_SERVER}/${REMOTE_SERVER_NAME} ( ${REMOTE_INTERFACE} ${REMOTE_DEVICE} ${REMOTE_IP} ${PORT} ) "
-                                printf "%-40s\t%-40s\t%-20s%-20s%-20s\n" "${LOCAL_INTERFACE}/${LOCAL_DEVICE}/${LOCAL_IP}" "${REMOTE_INTERFACE}/${REMOTE_DEVICE}/${REMOTE_IP}" "0" "0" "${MAX_SPEED}" >>${RESULT_FILE}
-                            fi
-                        )&
-                        else
-                            { ssh  -p ${ENV_SSH_PORT} ${REMOTE_CLIENT} ${CMD_CLI} ${OPTIONS} | tee ${REMOTE_RUN_IP_OUTPUT_DIR}; } || true
-                            BANDWITDH=$(cat ${REMOTE_RUN_IP_OUTPUT_DIR} | grep -A 1 "BW average" | grep -E "[0-9\.]+" | awk '{print $4 }') || true
-                            PPS=$(cat ${REMOTE_RUN_IP_OUTPUT_DIR} | grep -A 1 "BW average" | grep -E "[0-9\.]+" | awk '{print $5 }') || true
-                            if [ -n "${BANDWITDH}" ]; then
-                                printf "%-40s\t%-40s\t%-20s%-20s%-20s\n" "${LOCAL_INTERFACE}/${LOCAL_DEVICE}/${LOCAL_IP}" "${REMOTE_INTERFACE}/${REMOTE_DEVICE}/${REMOTE_IP}" "${BANDWITDH}" "${PPS}" "${MAX_SPEED}" >>${RESULT_FILE}
-                            else
-                                echo "error, ${REMOTE_CLIENT}/${REMOTE_CLIENT_NAME}( ${LOCAL_INTERFACE} ${LOCAL_DEVICE} ${LOCAL_IP} ) failed to test server ${REMOTE_SERVER}/${REMOTE_SERVER_NAME} ( ${REMOTE_INTERFACE} ${REMOTE_DEVICE} ${REMOTE_IP} ${PORT} ) "
-                                printf "%-40s\t%-40s\t%-20s%-20s%-20s\n" "${LOCAL_INTERFACE}/${LOCAL_DEVICE}/${LOCAL_IP}" "${REMOTE_INTERFACE}/${REMOTE_DEVICE}/${REMOTE_IP}" "0" "0" "${MAX_SPEED}" >>${RESULT_FILE}
-                            fi
-                        fi
+            MAX_SPEED=$(ethtool ${LOCAL_INTERFACE} | grep Speed | awk '{print $2}')
 
-                        echo "********* client ${REMOTE_CLIENT} : local ${LOCAL_INTERFACE}/${LOCAL_IP} -d ${LOCAL_DEVICE} -x ${LOCAL_INDEX}  ->  ${REMOTE_INTERFACE} ${REMOTE_IP} , -d ${REMOTE_DEVICE} -x ${REMOTE_INDEX} -p ${PORT} "
-
-                        (( PORT = PORT + 1))
-                    #fi
+            OPTIONS="-d ${LOCAL_DEVICE} -x ${LOCAL_INDEX} -p ${PORT} ${CMD_OPTIONS} ${REMOTE_IP}"
+            echo "client on ${REMOTE_CLIENT}/${REMOTE_CLIENT}: ${CMD_CLI} ${OPTIONS}"
+            if [ "${ASYNCHRONOUS}"x == "true"x ]; then
+                (
+                    { ssh  -p ${ENV_SSH_PORT} ${REMOTE_CLIENT} "${CMD_CLI} ${OPTIONS}" | tee ${REMOTE_RUN_IP_OUTPUT_DIR}; } || true
+                    BANDWITDH=$(cat ${REMOTE_RUN_IP_OUTPUT_DIR} | grep -A 1 "BW average" | grep -E "[0-9\.]+" | awk '{print $4 }') || true
+                    PPS=$(cat ${REMOTE_RUN_IP_OUTPUT_DIR} | grep -A 1 "BW average" | grep -E "[0-9\.]+" | awk '{print $5 }') || true
+                    if [ -n "${BANDWITDH}" ]; then
+                        printf "%-40s\t%-40s\t%-20s%-20s%-20s%-20s\n" "${LOCAL_INTERFACE}/${LOCAL_DEVICE}/${LOCAL_IP}" "${REMOTE_INTERFACE}/${REMOTE_DEVICE}/${REMOTE_IP}" "${BANDWITDH}" "${PPS}" "${MAX_SPEED} ${SAME_NETWORK_TRACK}" >>${RESULT_FILE}
+                    else
+                        echo "error, ${REMOTE_CLIENT}/${REMOTE_CLIENT_NAME}( ${LOCAL_INTERFACE} ${LOCAL_DEVICE} ${LOCAL_IP} ) failed to test server ${REMOTE_SERVER}/${REMOTE_SERVER_NAME} ( ${REMOTE_INTERFACE} ${REMOTE_DEVICE} ${REMOTE_IP} ${PORT} ) "
+                        printf "%-40s\t%-40s\t%-20s%-20s%-20s%-20s\n" "${LOCAL_INTERFACE}/${LOCAL_DEVICE}/${LOCAL_IP}" "${REMOTE_INTERFACE}/${REMOTE_DEVICE}/${REMOTE_IP}" "0" "0" "${MAX_SPEED} ${SAME_NETWORK_TRACK}" >>${RESULT_FILE}
+                    fi
+                )&
+            else
+                { ssh  -p ${ENV_SSH_PORT} ${REMOTE_CLIENT} " ${CMD_CLI} ${OPTIONS}" | tee ${REMOTE_RUN_IP_OUTPUT_DIR}; } || true
+                BANDWITDH=$(cat ${REMOTE_RUN_IP_OUTPUT_DIR} | grep -A 1 "BW average" | grep -E "[0-9\.]+" | awk '{print $4 }') || true
+                PPS=$(cat ${REMOTE_RUN_IP_OUTPUT_DIR} | grep -A 1 "BW average" | grep -E "[0-9\.]+" | awk '{print $5 }') || true
+                if [ -n "${BANDWITDH}" ]; then
+                    printf "%-40s\t%-40s\t%-20s%-20s%-20s%-20s\n" "${LOCAL_INTERFACE}/${LOCAL_DEVICE}/${LOCAL_IP}" "${REMOTE_INTERFACE}/${REMOTE_DEVICE}/${REMOTE_IP}" "${BANDWITDH}" "${PPS}" "${MAX_SPEED} ${SAME_NETWORK_TRACK}" >>${RESULT_FILE}
+                else
+                    echo "error, ${REMOTE_CLIENT}/${REMOTE_CLIENT_NAME}( ${LOCAL_INTERFACE} ${LOCAL_DEVICE} ${LOCAL_IP} ) failed to test server ${REMOTE_SERVER}/${REMOTE_SERVER_NAME} ( ${REMOTE_INTERFACE} ${REMOTE_DEVICE} ${REMOTE_IP} ${PORT} ) "
+                    printf "%-40s\t%-40s\t%-20s%-20s%-20s%-20s\n" "${LOCAL_INTERFACE}/${LOCAL_DEVICE}/${LOCAL_IP}" "${REMOTE_INTERFACE}/${REMOTE_DEVICE}/${REMOTE_IP}" "0" "0" "${MAX_SPEED} ${SAME_NETWORK_TRACK}" >>${RESULT_FILE}
                 fi
             fi
+
         done <${REMOTE_INFOR_DIR}/${REMOTE_CLIENT}
+
+        echo "======= next server device"
+        (( PORT = PORT + 1))
     done <${REMOTE_INFOR_DIR}/${REMOTE_SERVER}
 
     printf "_____________________________________________________________________________________________________________________________________________________\n" >>${RESULT_FILE}
@@ -201,6 +210,9 @@ RunPerOnHost() {
     }
     PORT=${START_PORT}
 
+    echo "clean all server on ${REMOTE_HOST}"
+    ssh  -p ${ENV_SSH_PORT} ${REMOTE_HOST} " PID=\`ps aux | grep ${CMD_CLI} | grep -v grep | awk '{print \$2}' \` ; [ -n \"\${PID}\" ] && { echo \"\${PID}\" | xargs -n 1 -i  kill -9 {} ; } " || true
+
     while read LINE; do
         REMOTE_DEVICE=$(echo "${LINE}" | awk '{print $1}')
         REMOTE_INTERFACE=$(echo "${LINE}" | awk '{print $2}')
@@ -215,12 +227,9 @@ RunPerOnHost() {
         OPTIONS+=" -p ${PORT} "
         echo "server on remote ${REMOTE_HOST} for ${REMOTE_INTERFACE} with ${REMOTE_IP}: ${CMD_CLI} ${OPTIONS}"
         (
-            ssh  -p ${ENV_SSH_PORT} ${REMOTE_HOST} " PID=\`ps aux | grep ${CMD_CLI} | grep -v grep | awk '{print \$2}' \` ; [ -n \"\${PID}\" ] && { echo \"\${PID}\" | xargs -n 1 -i  kill -9 {} ; } ; ${CMD_CLI} ${OPTIONS} " || true
+            ssh  -p ${ENV_SSH_PORT} ${REMOTE_HOST} "${CMD_CLI} ${OPTIONS} " || true
             #ssh  -p ${ENV_SSH_PORT} ${REMOTE_HOST} "${CMD_CLI} ${OPTIONS} " &>/dev/null
         )&
-
-        # debug
-        echo "********* server ${REMOTE_HOST} : for ${REMOTE_INTERFACE} ${REMOTE_IP} , -d ${REMOTE_DEVICE} -x ${REMOTE_INDEX} -p ${PORT} "
 
         ((PORT=PORT+1))
 
@@ -232,44 +241,38 @@ RunPerOnHost() {
 TestRdma() {
     rm -rf ${RESULT_DIR}/*
 
-    echo " run pair test between: ${POD_IP_LIST} ${LOCAL_IP}  "
+    ALL_HOST_LIST="${1}"
+
+    echo " run pair test between: ${ALL_HOST_LIST}   "
 
     echo "------------------ run server on all devices of each node ------------------"
-    for ADDR in ${POD_IP_LIST} ${LOCAL_IP}; do
-        RunPerOnHost "${ADDR}"
+    for ADDR in ${ALL_HOST_LIST} ; do
+       RunPerOnHost "${ADDR}"
     done
     echo ""
-    # in case that client will be killed
     sleep 2
 
     CLIENT_HOST=""
     SERVER_HOST=""
     CLIENT_NAME=""
     SERVER_NAME=""
-    COUNTER=0
-    for ADDR in ${POD_IP_LIST} ${LOCAL_IP}; do
+    for ADDR in ${ALL_HOST_LIST} ; do
         if [ -z "${CLIENT_HOST}" ] ; then
             CLIENT_HOST="${ADDR}"
             CLIENT_NAME=$( GetNodeName ${CLIENT_HOST} )
-            ((COUNTER=COUNTER+1))
             continue
         fi
         if [ -z "${SERVER_HOST}" ] ; then
             SERVER_HOST="${ADDR}"
             SERVER_NAME=$( GetNodeName ${SERVER_HOST} )
-            ((COUNTER=COUNTER+1))
         fi
-        echo "------------------ run communication from ${CLIENT_HOST}/${CLIENT_NAME} to ${SERVER_HOST}/${SERVER_NAME} ------------------"
+        echo "------------------ test communication from ${CLIENT_HOST}/${CLIENT_NAME} to ${SERVER_HOST}/${SERVER_NAME} ------------------"
         ( RunClient "${CLIENT_HOST}" "${SERVER_HOST}" )&
         CLIENT_HOST=""
         SERVER_HOST=""
         CLIENT_NAME=""
         SERVER_NAME=""
-        COUNTER=0
     done
-    if (( COUNTER != 0 )) ; then
-        echo "host ${ADDR} is still free, need a pair"
-    fi
     echo ""
     wait 
 
@@ -303,7 +306,15 @@ CMD_OPTIONS="${BW_CMD_OPTIONS}"
 echo "run ${LOOP_TIMES} times with duration ${DURATION} of ${LOOP_TIMES} round, asynchronously is ${ASYNCHRONOUS}"
 for ((i=1;i<=${LOOP_TIMES};i++)); do
     echo "===================================== round ${i} ===================================="
-    TestRdma
+
+    # run test on the same network track in sequential order
+    TestRdma "${POD_IP_LIST} ${LOCAL_IP}"
+
+    # run test on the same network track in reverse order
+    # 把 ${LOCAL_IP} 放到前面，${POD_IP_LIST} 放到后面，这样，当是奇数个节点时，避免有主机覆盖不到测试
+    TestRdma "${LOCAL_IP} ${POD_IP_LIST} "
+
+
     echo ""
 done
 
