rdma-tools: cuda
Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

diff --git a/.github/workflows/ImageRdmaTools.yaml b/.github/workflows/ImageRdmaTools.yaml
--- a/.github/workflows/ImageRdmaTools.yaml
+++ b/.github/workflows/ImageRdmaTools.yaml
@@ -24,6 +24,12 @@ on:
         description: 'sha, branch or tag for code'
         required: true
         default: main
+      baseImageCudaVersion:
+        description: 'cuda verison for base image'
+        required: false
+      baseImageOSVersion:
+        description: 'os verison for base image'
+        required: false
 
 permissions: write-all
 
@@ -37,6 +43,8 @@ jobs:
       build_platform: ${{ env.build_platform }}
       upload_artifact: ${{ env.upload_artifact }}
       dockerfile_dirctory: ${{ env.dockerfile_dirctory }}
+      baseImageFullName: ${{ env.baseImageFullName }}
+      image_tag: ${{ env.image_tag }}
     steps:
       - name: get information
         run: |
@@ -49,6 +57,12 @@ jobs:
             echo "dockerfile_dirctory=${{ env.DOCKERFILE_PATH }}" >> $GITHUB_ENV
             echo "build_platform=linux/amd64,linux/arm64" >> $GITHUB_ENV
             echo "upload_artifact=false" >> $GITHUB_ENV
+            if [ -n "${{ github.event.inputs.baseImageCudaVersion }}" ] ; then
+                baseImageCudaVersion=${{ github.event.inputs.baseImageCudaVersion }}
+            fi
+            if [ -n "${{ github.event.inputs.baseImageOSVersion }}" ] ; then
+                baseImageOSVersion=${{ github.event.inputs.baseImageOSVersion }}
+            fi
           elif ${{ github.event_name == 'push' }} ; then
             echo "call by push tag"
             echo "code_sha=${GITHUB_REF##*/}" >> $GITHUB_ENV
@@ -67,6 +81,40 @@ jobs:
             echo "build_platform=linux/amd64" >> $GITHUB_ENV
             echo "upload_artifact=false" >> $GITHUB_ENV
           fi
+          echo "get base image"
+          if [ -n "${baseImageCudaVersion}" ] && [ -n "${baseImageOSVersion}" ] ; then
+              export BASEIMAGE_CUDA_VERISON=${baseImageCudaVersion}
+              export BASEIMAGE_OS_VERISON=${baseImageOSVersion}
+          fi
+          source ${{ env.DOCKERFILE_PATH }}
+          echo "baseImageFullName=${BASEIMAGE_FULL_NAME}" >> $GITHUB_ENV
+
+      - name: Checkout Source Code
+        uses: actions/checkout@v4
+        with:
+          persist-credentials: false
+          ref: ${{ env.code_sha }}
+
+      - name: Getting Build Arg
+        id: arg
+        run: |
+          echo "get base image"
+          if [ -n "${baseImageCudaVersion}" ] && [ -n "${baseImageOSVersion}" ] ; then
+              export BASEIMAGE_CUDA_VERISON=${baseImageCudaVersion}
+              export BASEIMAGE_OS_VERISON=${baseImageOSVersion}
+          fi
+          source ${{ env.DOCKERFILE_PATH }}
+          echo "baseImageFullName=${BASEIMAGE_FULL_NAME}" >> $GITHUB_ENV
+          echo "get image tag"
+          image_tag=${{ inputs.image_tag }}
+          if [ -n "${image_tag}" ]; then
+             echo "image_tag=${BASEIMAGE_CUDA_VERISON}-${{ inputs.image_tag }}" >> $GITHUB_ENV
+          else
+             dockerfile_dirctory=${{ inputs.dockerfile_dirctory }}
+             image_tag=$( git ls-tree --full-tree HEAD -- ${dockerfile_dirctory} | awk '{ print $3 }' )
+             [ -n "${image_tag}" ] || { echo "error, failed to get image_tag from commit id"; exit 1 ; }
+             echo "image_tag=${BASEIMAGE_CUDA_VERISON}-${image_tag}" >> $GITHUB_ENV
+          fi
 
   call-workflow:
     needs: [get_info]
@@ -78,5 +126,6 @@ jobs:
       dockerfile_dirctory: ${{ needs.get_info.outputs.dockerfile_dirctory }}
       build_platform: ${{ needs.get_info.outputs.build_platform }}
       upload_artifact: ${{ needs.get_info.outputs.upload_artifact }}
-      # leave image_tag empty , use commit id for tag
+      baseImageFullName: ${{ needs.get_info.outputs.baseImageFullName }}
+      image_tag: ${{ needs.get_info.outputs.image_tag }}
     secrets: inherit
